import Artwork1 from "../assets/images/1.png"; 
import Artwork2 from "../assets/images/3.png"; 
import Artwork3 from "../assets/images/6.jpg"; 
import Artwork4 from "../assets/images/7.png"; 
import Artwork5 from "../assets/images/11.png"; 
import Artwork6 from "../assets/images/12.png"; 
import Artwork7 from "../assets/images/13.png"; 
import Artwork8 from "../assets/images/14.png"; 
import Artwork9 from "../assets/images/16.png";

export const ARTWORKS = [ 
  {
    id: 1,
    image: Artwork1,
    title: "Le Désespéré",
    dimensions: "Dimension: 60 x 120 cm",
    priceValue: 8500000,
    height: 60, 
    width: 120, 
    price: "Rp. 8.500.000",
    artist: "Gustave Courbet",
    frameDetails: "With wooden frame",
    style: "Realistic",
  },
  {
    id: 2,
    image: Artwork2,
    title: "Umbra Fenestre",
    dimensions: "Dimension: 60 cm x 90 cm",
    price: "Rp. 2.500.000",
    artist: "Studio Artist",
    height: 60,
    width: 90,
    priceValue: 2500000,
    frameDetails: "Unframed",
    style: "Geometric",
  },
  {
    id: 3,
    image: Artwork3,
    title: "White Symphony",
    dimensions: "Dimension: 80 x 120 cm",
    price: "Rp. 8.200.000",
    artist: "Ballet Artwork",
    height: 80,
    width: 120,
    priceValue: 8200000,
    frameDetails: "With frame",
    style: "Illustrative",
  },
  {
    id: 4,
    image: Artwork4,
    title: "Mona Lisa",
    dimensions: "Dimension: 70 x 100 cm",
    price: "Rp. 4.000.000",
    artist: "Leonardo da Vinci",
    height: 70,
    width: 100,
    priceValue: 4000000,
    frameDetails: "Museum grade frame",
    style: "Realistic",
  },
  {
    id: 5,
    image: Artwork5,
    title: "Oculus Profundus",
    dimensions: "Dimension: 80 x 120 cm",
    price: "Rp. 8.000.000",
    artist: "Surreal Studio",
    height: 80,
    width: 120,
    priceValue: 8000000,
    frameDetails: "Floating frame",
    style: "Surrealist",
  },
  {
    id: 6,
    image: Artwork6,
    title: "Harmonia Mundi",
    dimensions: "Dimension: 70 x 110 cm",
    price: "Rp. 3.500.000",
    artist: "Urban Theme",
    height: 70,
    width: 110,
    priceValue: 3500000,
    frameDetails: "Black metal frame",
    style: "Abstract",
  },
  {
    id: 7,
    image: Artwork7,
    title: "The Persistence",
    dimensions: "Dimension: 60 x 90 cm",
    price: "Rp. 3.400.000",
    artist: "Salvador Dalí",
    height: 60,
    width: 90,
    priceValue: 3400000,
    frameDetails: "With frame",
    style: "Surrealist",
  },
  {
    id: 8,
    image: Artwork8,
    title: "White Symphony",
    dimensions: "Dimension: 80 x 120 cm",
    price: "Rp. 8.200.000",
    artist: "Ballet Artwork",
    height: 80,
    width: 120,
    priceValue: 8200000,
    frameDetails: "With frame",
    style: "Illustrative",
  },
  {
    id: 9,
    image: Artwork9,
    title: "Mona Lisa",
    dimensions: "Dimension: 70 x 100 cm",
    price: "Rp. 4.000.000",
    artist: "Leonardo da Vinci",
    height: 70,
    width: 100,
    priceValue: 4000000,
    frameDetails: "Museum grade frame",
    style: "Realistic",
  },
  {
    id: 10,
    image: Artwork1,
    title: "The Starry Night",
    dimensions: "Dimension: 70 x 110 cm",
    price: "Rp. 3.800.000",
    artist: "Vincent van Gogh",
     height: 70,
    width: 110,
    priceValue: 3800000,
    frameDetails: "Simple wood frame",
    style: "Abstract",
  },
  {
    id: 11,
    image: Artwork3,
    title: "Umbra Fenestre",
    dimensions: "Dimension: 60 x 90 cm",
    price: "Rp. 2.500.000",
    artist: "Studio Artist",
    height: 60,
    width: 90,
    priceValue: 2500000,
    frameDetails: "Unframed",
    style: "Geometric",
  },
  {
    id: 12,
    image: Artwork5,
    title: "Le Désespéré",
    dimensions: "Dimension: 60 x 120 cm",
    price: "Rp. 8.500.000",
    artist: "Gustave Courbet",
    height: 60,
    width: 120,
    priceValue: 8500000,
    frameDetails: "With wooden frame",
    style: "Realistic",
  },
];